import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from '../src/components/layout/nav'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Blockfri, know what the crypto market is offering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
    </div>
  )
}

export default Home
